// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:f0eced49-7c0e-40cc-bc6a-2d4b623f044d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_keom9fuep",
    "aws_user_pools_web_client_id": "6kgv5jjo9lcb2d4q8r7g4jag35"
    };


export default awsmobile;
